/// Generated by AssetsRefGenerator on 2022/01/13
class Res {
  static const String ab = "assets/ab.png";
  static const String avt = "assets/avt.png";
  static const String bg = "assets/bg.png";
  static const String icon_bottom_right = "assets/icon-bottom-right.png";
  static const String icon_google = "assets/icon-google.png";
  static const String icon_top_right = "assets/icon-top-right.png";
  static const String icon_user = "assets/icon-user.png";
  static const String logo = "assets/logo.png";
  static const String splash_bg = "assets/splash_bg.png";
}
