/// Generated by AssetsRefGenerator on 2022/02/09
class Res {
  static const String ab = "assets/ab.png";
  static const String avt = "assets/avt.png";
  static const String bg = "assets/bg.png";
  static const String default_group_avatar = "assets/default-group-avatar.png";
  static const String default_user_avatar = "assets/default-user-avatar.jpg";
  static const String home_icon = "assets/home_icon.png";
  static const String icon_bottom_right = "assets/icon-bottom-right.png";
  static const String icon_google = "assets/icon-google.png";
  static const String icon_top_right = "assets/icon-top-right.png";
  static const String icon_user = "assets/icon-user.png";
  static const String logo = "assets/logo.png";
  static const String mini_logo = "assets/mini_logo.png";
  static const String profile_header = "assets/profile_header.png";
  static const String splash_bg = "assets/splash_bg.png";
}
